export const USER_REGISTER_REQUEST = "USER_REGISTER_REQUEST";
export const USER_REGISTER_SUCCESS = "USER_REGISTER_SUCCESS";
export const USER_REGISTER_FALIURE = "USER_REGISTER_FALIURE";

export const USER_LOGIN_REQUEST = "USER_LOGIN_REQUEST";
export const USER_LOGIN_SUCCESS = "USER_LOGIN_SUCCESS";
export const USER_LOGIN_FALIURE = "USER_LOGIN_FALIURE";

export const USER_LOGOUT = "USER_LOGOUT";

export const ALL_USERS_DATA_REQUEST = "ALL_USERS_DATA_REQUEST";
export const ALL_USERS_DATA_SUCCESS = "ALL_USERS_DATA_SUCCESS";
export const ALL_USERS_DATA_FALIURE = "ALL_USERS_DATA_FALIURE";